[tool.poetry]
name = "projeto1"
version = "0.1.0"
description = "Projeto 1 do Poetry"
authors = ["Janaína"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "1.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
