[tool.poetry]
name = "projeto2"
version = "0.1.0"
description = "Projeto 2 em Poetry"
authors = ["Janaína"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "1.23.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
